-- Backfill: Set ever_set_username = true for users whose username doesn't match auto-generated patterns
-- Pattern 1 (UserContext fallback): AdjectiveNoun + 0-3 digits (e.g., "HappyStar123")
-- Pattern 2 (usernameGenerator): Word1Word2-4digits (e.g., "WinterBayesian-1234")

UPDATE users SET ever_set_username = true
WHERE username IS NOT NULL
  AND username !~ '^(Happy|Cool|Bright|Swift|Bold|Calm|Kind|Wise|Brave|Gentle)(Star|Wave|Cloud|River|Mountain|Forest|Ocean|Valley|Meadow|Creek)[0-9]*$'
  AND username !~ '^(Winter|Solstice|Candlelight|Starlight|Twilight|Dawn|Darkness|Light|Cosmos|Void|Galaxy|Nebula|Eclipse|Equinox|Midwinter|Stellar|Horizon|Dusk|Aurora|Eternal|Frozen|Silent|Ancient|Cosmic|Celestial|Astronomical|Infinite|Cold|Snow|Ice|Frost|Crystal|Night|Moon|Star|Comet|Meteor|Orbit|Gravity|Entropy|Quantum|Singularity|Event|Waning|Rising|Setting|Axial)(Bayesian|Rational|Epistemic|Prior|Update|Evidence|Logic|Reason|Calibrated|Fermi|Posterior|Coherent|Utility|Expected|Optimal|Meta|Aligned|Consequent|Deductive|Inductive|Abductive|Heuristic|Bias|Truthseeker|Skeptic|Empirical|Fallible|Falsifiable|Credence|Likelihood|Inference|Hypothesis|Theorem|Axiom|Principle|Instrumental|Terminal|Effective|Altruist|Utilitarian|Consequentialist|Reflective|Coherentist|Foundationalist|Pragmatic|Analytic|Synthetic)-[0-9]{4}$'
  AND username !~ '^(Bayesian|Rational|Epistemic|Prior|Update|Evidence|Logic|Reason|Calibrated|Fermi|Posterior|Coherent|Utility|Expected|Optimal|Meta|Aligned|Consequent|Deductive|Inductive|Abductive|Heuristic|Bias|Truthseeker|Skeptic|Empirical|Fallible|Falsifiable|Credence|Likelihood|Inference|Hypothesis|Theorem|Axiom|Principle|Instrumental|Terminal|Effective|Altruist|Utilitarian|Consequentialist|Reflective|Coherentist|Foundationalist|Pragmatic|Analytic|Synthetic)(Winter|Solstice|Candlelight|Starlight|Twilight|Dawn|Darkness|Light|Cosmos|Void|Galaxy|Nebula|Eclipse|Equinox|Midwinter|Stellar|Horizon|Dusk|Aurora|Eternal|Frozen|Silent|Ancient|Cosmic|Celestial|Astronomical|Infinite|Cold|Snow|Ice|Frost|Crystal|Night|Moon|Star|Comet|Meteor|Orbit|Gravity|Entropy|Quantum|Singularity|Event|Waning|Rising|Setting|Axial)-[0-9]{4}$';
